DROP TABLE IF EXISTS tdl CASCADE;
DROP TABLE IF EXISTS user CASCADE;
CREATE TABLE tdl (
	tdl_id integer generated by default as identity,
	priority integer not null check (priority<=5 AND age>=1),
	taskStatus ENUM('PENDING', 'COMPLETED', 'CANCELLED'),
	date varchar(255) not null,
	task varchar(255) not null,
	fk_user_id integer,
	primary key (tdl_id)
);
CREATE TABLE user (
	user_id integer generated by default as identity,
	name varchar(255),
	primary key (user_id)
);
ALTER TABLE tdl add constraint UK_8qrhl5wlohdjoko9nrorkdjkp unique (name);
ALTER TABLE user add constraint UK_9ome4qyhbd8a1n39dvjsxjks0 unique (name);
ALTER TABLE tdl add constraint FKdtss7ab4sx4oagfqyacono43a foreign key (fk_user_id) references pond on delete cascade;